# Generated by Django 5.2.17 on 2026-09-21 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandeCompte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_complet", models.CharField(max_length=120)),
                ("telephone", models.CharField(max_length=16)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("Dakar", "Dakar"),
                            ("Diourbel", "Diourbel"),
                            ("Fatick", "Fatick"),
                            ("Kaffrine", "Kaffrine"),
                            ("Kaolack", "Kaolack"),
                            ("Kédougou", "Kédougou"),
                            ("Kolda", "Kolda"),
                            ("Louga", "Louga"),
                            ("Matam", "Matam"),
                            ("Saint-Louis", "Saint-Louis"),
                            ("Sédhiou", "Sédhiou"),
                            ("Tambacounda", "Tambacounda"),
                            ("Thiès", "Thiès"),
                            ("Ziguinchor", "Ziguinchor"),
                        ],
                        max_length=40,
                    ),
                ),
                ("ia", models.CharField(max_length=120)),
                ("ief", models.CharField(max_length=120)),
                (
                    "type_piece",
                    models.CharField(
                        choices=[
                            ("cni", "Carte nationale d'identité"),
                            ("passeport", "Passeport"),
                            ("carte_electeur", "Carte d'électeur"),
                            ("carte_pro", "Carte professionnelle"),
                            ("autre", "Autre pièce"),
                        ],
                        max_length=20,
                    ),
                ),
                ("numero_piece", models.CharField(max_length=60)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("nouvelle", "Nouvelle"),
                            ("traitee", "Traitée"),
                            ("rejetee", "Rejetée"),
                        ],
                        default="nouvelle",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
