# Generated by Django 5.2.17 on 2026-09-22 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_demandecompte"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="demandecompte",
            name="compte_cree",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="demandecompte",
            name="note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="demandecompte",
            name="traite_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="demandecompte",
            name="traite_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="demandes_traitees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
